platform :ios, '9.0'
use_frameworks!

target 'Unrealm_Example' do
  pod 'Unrealm', :path => '../'    
  
  target 'Unrealm_Tests' do
    inherit! :search_paths
  end
end

target 'Example with Abstraction' do
    
  target 'RealmStorage' do
		inherit! :search_paths
		
		pod 'Unrealm', :path => '../'
	end

end
