use_frameworks!

target 'Unrealm_Example' do
	platform :ios, '11.0'
  pod 'Unrealm', :path => '../'    
  
  target 'Unrealm_Tests' do
    inherit! :search_paths
  end
end

target 'Example with Abstraction' do
	platform :ios, '11.0'
  target 'RealmStorage' do
		inherit! :search_paths
		
		pod 'Unrealm', :path => '../'
	end

end


# target 'Example with Mac' do
# 	platform :osx, '10.12'
#  	pod 'Unrealm', :path => '../'

# end

